### ISSUE TITLE
Komplettering - vecka 1

### ISSUE THREAD

**Issue by augustb** [fkam/indaproject#16]
Hej, er projektplan beskriver ert projekt i detalj, och delar upp arbetet i lämpliga beståndsdelar. Jag tycker sättet ni använder milestones är proffsigt och tydligt, men jag tycker inte att det direkt ger en uppfattning om tidsåtgången för respektive version av projektet. Men ni har ju själva bedömt tidsåtgången, så det löser ni säkert. 

Ni behöver däremot komplettera er projektbeskrivning, som (vilket ni säkert förstår själva, i och med att den är tom!) inte beskriver ert projekt i tillräcklig detalj. Betänk följande:

The Project Description should contain:
A short, clear description of the project
Documentation on how to install and use the project (this will evolve)
Give a description of your testing strategy

Jag behöver er komplettering innan denna veckas slut för att jag ska kunna godkänna er i Rapp. Ser fram emot att se ert projekt fortlöpa!

**Comment by theagentd** [comment]
Jag protesterar mot auktoriteter.

**Comment by theagentd** [comment]
Vi fixar detta ASAP. =P

**Comment by fkam** [comment]
Vi har uppdaterat Readme filen, ta en titt.

**Comment by augustb** [comment]
Hej, tack för kompletteringen. Ni är godkända på vecka 1.
